### ISSUE TITLE
#[derive(Response)]    |          ^^^^^^^^ use of undeclared type or module `http`

### ISSUE THREAD

**Issue by denniscollective** [carllerche/tower-web#183]
I'm unable to derive a response, yielding the error in the title.

I'm on stable (1.32.0), with edition 2018 enabled.

Sorry if this is not appropriate issue– but I'm a beginner and have spent a few hours trying to get around this issue.

Thanks for your work!

**Comment by carllerche** [comment]
Interesting. Do you have a repro?

**Comment by emschwartz** [comment]
I'm also seeing this issue. [This](https://github.com/emschwartz/interledger-rs/pull/36) is the PR and [this](https://circleci.com/gh/emschwartz/interledger-rs/106) is the CI build with the error.

**Comment by denniscollective** [comment]
Here's a trivial repro case:

```rust
#[macro_use]
extern crate tower_web;

extern crate tokio;

use tower_web::ServiceBuilder;

pub fn main() {
    let addr = "127.0.0.1:8080".parse().expect("Invalid address");
    println!("Listening on http://{}", addr);


    ServiceBuilder::new()
        .resource(Routes {})
        .run(&addr)
        .unwrap();
}


#[derive(Clone, Debug, Response)]
pub struct Routes {}


impl_web! {
    impl Routes {
        #[get("/")]
        fn hello_world( & self ) -> Result < String, () > {
            Ok(format!("HEY BUCKO!"))
        }
    }
}
```

this works without the derive Response. 

I hit this when trying to use the handlebars templating, which necessitated deriving a response (the content type and template macros did not raise any errors)

**Comment by denniscollective** [comment]
this is using:

```toml
[package]
name = "wat"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = "^0.1.15"
tower-web = "^0.3.4"
```

**Comment by 0xpr03** [comment]
Same error here with https://paste.ee/p/HEvPJ
Also I'm hitting "unimplemented!" errors and "web is a reserved keyboard" !?

**Comment by 0xpr03** [comment]
I just retried and I get the same error with your [handlebars example](https://github.com/carllerche/tower-web/blob/master/examples/html_handlebars.rs)
Using
```toml
[dependencies]
tower-web="0.3"
tokio="0.1"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
serde_plain = "0.3.0"
serde_urlencoded = "0.5.1"
```

**Comment by 0xpr03** [comment]
@denniscollective @emschwartz I've fixed the compile error when adding the http crate.
So to get a) Extract and b) Response to run you need the following cargo.toml
```toml
[dependencies]
tower-web="0.3"
tokio="0.1"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
serde_plain = "0.3.0"
serde_urlencoded = "0.5.1"
http = "0.1.7"
```

**Comment by carllerche** [comment]
Thanks! I will investigate now.

**Comment by carllerche** [comment]
Ah, I bet edition 2018 has something to do with it...

**Comment by carllerche** [comment]
I opened #185 to fix the `http` issue.

Fixing the `_serde` issue will require an upstream change: https://github.com/serde-rs/serde/issues/1487

As a work around for now, you may include the following dependencies in your `Cargo.toml`:

```toml
serde = "1"
http = "0.1"
```

Additionally, Rust 2018 macro imports are not supported yet. Supporting this will require a breaking change release to tower-web.

For now, using `[macro_use] extern crate tower_web;` works.
